spring.application.name=user-registration
spring.data.mongodb.uri=mongodb+srv://hkenula:YLMK03AyRwXxVDjM@cluster0.zpcamke.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=userdb