spring.data.mongodb.uri=https://cloud.mongodb.com/v2/680e2ad533ac2971d5270174#/metrics/replicaSet/680e2b1181774d11a9e90c41/explorer/learningProgress/Progress/find

spring.data.mongodb.database=Progress

# OAuth 2.0 Configuration (Google)
spring.security.oauth2.client.registration.google.client-id=your-google-client-id
spring.security.oauth2.client.registration.google.client-secret=your-google-client-secret
spring.security.oauth2.client.registration.google.scope=openid,profile,email